import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex justify-center items-center h-screen w-full"
    >
      <div className="p-10 bg-slate-300 rounded">
        {children}
      </div>
    </div>
  );
}
